name: CI/CD Pipeline for FastAPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run FastAPI Tests (optional)
      - name: Run FastAPI tests
        run: |
          uvicorn main:app --port 8000 &
          sleep 5
          # Here you would run your Katalon Studio tests
          # You can use Katalon CLI to run tests or Postman/Newman, or Pytest, etc.

      # Step 5: Deploy (optional, if using Railway or other service)
      - name: Deploy to Railway
        run: |
          # Deploy script for Railway or other deployment services
          echo "Deploying to Railway"
